export const FETCH_TODO_LIST_START = 'FETCH_TODO_LIST_START'
export const FETCH_TODO_LIST_SUCCESS = 'FETCH_TODO_LIST_SUCCESS'
export const FETCH_TODO_LIST_ERROR = 'FETCH_TODO_LIST_ERROR'

export const FETCH_TODO_START = 'FETCH_TODO_START'
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
export const FETCH_TODO_ERROR = 'FETCH_TODO_ERROR'
